name: tanker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.18.0
  localstore: ^1.3.5
  material_design_icons_flutter: ^6.0.7096
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  image_path: "assets/images/tank.png"
  android: true
  ios: false
